blog/urls.py
from django.urls import path
from blog.views import show_post, post_detail, upload, show_json, addUpvote, addDownvote, show_json_by_tag, show_json_by_id, add_post, show_post_by_tag, show_tag

app_name = 'blog'

urlpatterns = [
    path('', show_post, name='show_post'),
    path('details/', post_detail, name='post_detail'),
    path('add-post/', upload, name='upload'),
    path('add-post-flutter/', add_post, name='add_post'),
    path('show-tag-flutter/<str:tag>', show_post_by_tag, name='show_post_by_tag'),
    path('json/', show_json, name='show_json'),
    path('jsontag/', show_tag, name='show_tag'),
    path('json/<str:tag>', show_json_by_tag, name='show_json_by_tag'),
    path('json/id/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('updateUpvote/<int:id>', addUpvote, name='addUpvote'),
    path('updateDownvote/<int:id>', addDownvote, name='addDownvote'),
]

donation/urls.py
from django.urls import path
from donation.views import *

app_name = 'blog'

urlpatterns = [
    path('', show_donation, name='show_donation'),
    path('opened-donatee', show_donation_user, name='show_donation_user'),
    path('details/<int:id>', donation_detail, name='donation_detail'),
    path('delete/<int:id>', donation_delete, name='donation_delete'),
    path('json/', show_json, name='show_json'),
    path('json-admin/', show_json_admin, name='show_json_admin'),
    path('json-user/', show_json_user, name='show_json_user'),
    path('details/donate/<int:id>', donate, name='donate'),
    path('delete-admin/<int:id>', delete_by_admin, name='delete_by_admin'),
    path('change-status/<int:id>', change_status_donatee, name='change_status_donatee'),
    path('json-with-name/', show_json_with_opener, name='show_json_with_opener'),
    path('json-verified/', show_json_verified, name='show_json_verified'),
    path('donate/', donate_flutter, name='donate_flutter'),
    path('add-donatee/', add_donatee, name='add_donatee'),
    path('json-by-user/', show_json_by_user, name='show_json_by_user'),
    path('close/', donation_close, name='donation_close'),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', show_index, name='show_index'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json-user/', json_user, name='json_user'),
    path('change/<int:id>', change_status_user, name='change_status_user'),
    path('delete/<int:id>', delete_user, name='delete_user'),
    path('profile/', show_profile, name='profile'),
    path('add-message/', add_message, name='add_message'),
    path('json-message/', show_json_message, name='show_json_message'),
    path('delete-msg/<int:id>', delete_message, name='delete_message'),
    path('json-message-name/', show_json_message_with_sender, name='show_json_message_with_sender')
]

nutrious/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('calorietracker/', include('calorietracker.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('foodsharing/', include('foodsharing.urls')),
    path('recipe/', include('recipe.urls')),
    path('auth/', include('authentication.urls'))
]

donation/models.py
from django.db import models
from home.models import AppUser
from django.core.validators import MinValueValidator

# Create your models here.
class Donatee(models.Model):
    name = models.CharField(max_length=200)
    opener = models.ForeignKey(AppUser, on_delete= models.CASCADE, blank=True, null=True)
    description = models.TextField()
    amountNeeded = models.IntegerField(default=100000, validators=[MinValueValidator(100000)])
    collectedFunds = models.IntegerField(default=0)
    is_verified = models.BooleanField(default=False)

    def getAuthorName(self):
        return self.opener.username

donation/forms.py
from django import forms
from donation.models import Donatee

class OpenDonationForm(forms.ModelForm):
    class Meta:
       model = Donatee
       fields = ('name', 'description', 'amountNeeded')

       widgets = {
            'description': forms.Textarea(attrs={'cols': 24, 'rows': 4}),
       }


    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['amountNeeded'].min_value = 100000

donation/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from donation.models import Donatee
from django.views.decorators.csrf import csrf_exempt
from donation.forms import OpenDonationForm

# Create your views here.
# Create your views here.
@login_required(login_url='/login/')
def show_donation(request):

    if request.method == 'POST':

        form = OpenDonationForm(request.POST)

        if form.is_valid():
            donatee = form.save()
            donatee.opener = request.user
            donatee.save()

            return redirect('donation:show_donation')

    else:
        form = OpenDonationForm()

    context = {
        'user' : request.user,
        'user_profile' : request.user.profile_pict_url,
        'form': form,
    }
    return render(request, "donation_page.html", context)

@login_required(login_url='/login/')
def show_donation_user(request):

    if request.POST.get('action') == 'post':
            name = request.POST.get('name')
            description = request.POST.get('description')
            amountNeeded = request.POST.get('amountNeeded')
            user = request.user
            obj_baru = Donatee(opener = user, name = name, description = description, amountNeeded = amountNeeded)
            obj_baru.save()

            return JsonResponse({'status': 'berhasil dibuka'}, status=200)

    else:
        form = OpenDonationForm()

    context = {
            'user' : request.user,
            'user_profile' : request.user.profile_pict_url,
            'form': form,
    }
    return render(request, "donation_page_user.html", context)

def show_json(request):
    data = Donatee.objects.filter(is_verified = True)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_admin(request):
    data = Donatee.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_user(request):
    data = Donatee.objects.filter(opener = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def donation_detail(request, id):
    post_detail = Donatee.objects.get(pk = id)
    context = {
        'postdetail' : post_detail
    }
    return render(request, "donation_details.html", context)

def donate(request, id):
    if request.POST.get('action') == 'post':
        donatee = Donatee.objects.get(id=id)
        donatee.collectedFunds = donatee.collectedFunds + int(request.POST.get('amount'))
        donatee.save()
        return redirect('donation:show_donation')

@csrf_exempt
def donation_delete(request, id):
    Donatee.objects.filter(id=id).delete()
    return JsonResponse({'status': 'berhasil ditutup'}, status=200)

@login_required(login_url='/login/')
def delete_by_admin(request, id):
    if request.user.is_admin:
        Donatee.objects.filter(id=id).delete()
        return JsonResponse({'status': 'Donatee is deleted successfully'})
    else:
        return JsonResponse({'status': 'Invalid deletion'}, status=403)

@login_required(login_url='/login/')
def change_status_donatee(request, id):
    if request.user.is_admin:
        donatee = Donatee.objects.get(id=id)
        donatee.is_verified = not donatee.is_verified
        donatee.save()
    else:
        return HttpResponse("Not allowed", status=403)
    return redirect('home:show_index')

@login_required(login_url='/login/')
def show_json_with_opener(request):
    list_of_donations = []
    donations = Donatee.objects.all()
    for donation in donations:
        donation_instance = {}
        donation_instance["pk"] = donation.id
        donation_instance["opener"] = donation.getAuthorName()
        donation_instance["name"] = donation.name
        donation_instance["description"] = donation.description
        donation_instance["amountNeeded"] = donation.amountNeeded
        donation_instance["collectedFunds"] = donation.collectedFunds
        donation_instance["isVerified"] = donation.is_verified
        list_of_donations.append(donation_instance)
    return JsonResponse({"data": list_of_donations})

@login_required(login_url='/login/')
def show_json_verified(request):
    list_of_donations = []
    donations = Donatee.objects.filter(is_verified = True)
    for donation in donations:
        donation_instance = {}
        donation_instance["pk"] = donation.id
        donation_instance["opener"] = donation.getAuthorName()
        donation_instance["name"] = donation.name
        donation_instance["description"] = donation.description
        donation_instance["amountNeeded"] = donation.amountNeeded
        donation_instance["collectedFunds"] = donation.collectedFunds
        donation_instance["isVerified"] = donation.is_verified
        list_of_donations.append(donation_instance)
    return JsonResponse({"data": list_of_donations})

@login_required(login_url='/login/')
def show_json_by_user(request):
    list_of_donations = []
    donations = Donatee.objects.filter(opener = request.user)
    for donation in donations:
        donation_instance = {}
        donation_instance["pk"] = donation.id
        donation_instance["opener"] = donation.getAuthorName()
        donation_instance["name"] = donation.name
        donation_instance["description"] = donation.description
        donation_instance["amountNeeded"] = donation.amountNeeded
        donation_instance["collectedFunds"] = donation.collectedFunds
        donation_instance["isVerified"] = donation.is_verified
        list_of_donations.append(donation_instance)
    return JsonResponse({"data": list_of_donations})

@csrf_exempt
def donate_flutter(request):
    if (request.method == 'POST'):
        id = request.POST.get('id')
        donatee = Donatee.objects.get(pk=int(id))
        donatee.collectedFunds = donatee.collectedFunds + int(request.POST.get('amount'))
        donatee.save()
        return JsonResponse({"data": "success"})

@csrf_exempt
def add_donatee(request):
    if (request.method == 'POST'):
        name = request.POST.get('name')
        description = request.POST.get('description')
        amountNeeded = int(request.POST.get('amountNeeded'))
        user = request.user
        obj_baru = Donatee(opener = user, name = name, description = description, amountNeeded = amountNeeded)
        obj_baru.save()

        return JsonResponse({'status': 'berhasil dibuka'}, status=200)

@csrf_exempt
def donation_close(request):
    if (request.method == 'POST'):
        id = request.POST.get('id')
        Donatee.objects.get(pk=int(id)).delete()
        return JsonResponse({'status': 'berhasil ditutup'}, status=200)

donation/templates/donation_details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Donatee Details</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function myFunction() {
        alert("Thank you for your donation! We hope that you keep donating to help others in need.");
    }

    $(document).on('submit', '#form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:"donate/{{ postdetail.pk }}",
            data:{
                amount:$('#amount').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(){
                document.getElementById("form").reset();
                window.location.href = "";
            },
        });
    });
</script>

<link rel="stylesheet" href="{% static '/invalidButton.css' %}" />
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 left  top">
            <div class="card-body">
                <h1>{% block title %} {{ postdetail.name }} {% endblock title %}</h1>
                <p class=" text-muted">Opener: {{ postdetail.getAuthorName }}</p>
                <p class="card-text ">Description: {{ postdetail.description | safe }}</p>
                <p class="card-text ">Amount Needed: {{ postdetail.amountNeeded | safe }}</p>
                <p class="card-text ">Collected Funds: {{ postdetail.collectedFunds | safe }}</p>
                <form id="form" method="POST" action="">
                    {% csrf_token %}
                    <p class="card-text">Donate: </p>
                    <input id="amount" type="number" name="amount" min="1000" placeholder="Minimum amount of donation is 1000" class="form-control" required>
                    <br>
                    <button onclick="myFunction()" class="btn btn-warning" type="submit" value="Donate">Donate</button>
                </form>
            </div>
        </div>

        <a class="m-1 btn btn-primary" href="{% url 'donation:show_donation' %}">Back</a>
    </div>
</div>

{% endblock content %}

donation/templates/donation_page.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Donation</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
<link rel="stylesheet" href="{% static '/donationPageStyle.css' %}" />
<link rel="stylesheet" href="{% static '/invalidButton.css' %}" />
<script src="{% static '/donationPageJS.js' %}"></script>
{% endblock meta %}

{% block content %}
<body>
{% if user.is_user %}
    <nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:show_index' %}">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row">
            {% if user.is_verified_user %}
            <a class="m-3 btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">Open Donations</a>
            {% endif %}
            <div class="dropdown m-auto mx-3">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    {% if user.is_verified_user %}
                    <li><a class="dropdown-item" href="{% url 'donation:show_donation_user' %}">Opened Donation(s)</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>
            </div>

            <!-- Pembeda dari user yang sudah verified dan belum adalah pada border dari profile picture -->
            {% if user.is_verified_user %}
            <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
            {% else %}
            <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
            {% endif %}
        </div>
    </div>
    </nav>

    <!-- Card berisi Donatee -->
    <div class="container my-5">
        <div class="row">
            <div id ="card"></div>
        </div>
    </div>

    <!-- Modal -->
    <div id="modal" class="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Open Donations</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="" id="form_modal">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <table>
                            <tr class="fieldWrapper">
                                {{ form.name.errors }}
                                <td class="p m-3">Donatee Name: </td>
                                <td class="m-3">
                                    <input type="text" id="{{form.name.id_for_label}}" name="{{form.name.html_name}}"
                                           class="form-control{% if form.name.errors %} is-invalid{% endif %}"
                                           value="{% if form.name.value %}{{form.name.value}}{% endif %}" placeholder="Name" required>
                                </td>
                            </tr>
                            <tr class="fieldWrapper">
                                {{ form.description.errors }}
                                <td class="p m-3">Description: </td>
                                <td class="m-3">
                                <textarea id="{{form.description.id_for_label}}" name="{{form.description.html_name}}"
                                          class="form-control{% if form.description.errors %} is-invalid{% endif %}"
                                          value="{% if form.description.value %}{{form.description.value}}{% endif %}" placeholder="Description" required> </textarea>
                                </td>
                            </tr>
                            <tr class="fieldWrapper">
                                {{ form.amountNeeded.errors }}
                                <td class="p m-3">Amount Needed: </td>
                                <td class="p m-3"><input type="number" id="{{form.amountNeeded.id_for_label}}" name="{{form.amountNeeded.html_name}}"
                                           class="form-control{% if form.amountNeeded.errors %} is-invalid{% endif %}"
                                           value="{% if form.amountNeeded.value %}{{form.amountNeeded.value}}{% endif %}" placeholder="Min: 100000" min="100000" required></td>
                            </tr>
                            <tr>
                                <td class="p m-3"><button class="btn btn-warning" type="submit" value="Open Donatee">Open Donatee</button></td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% else %}
<nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row">
            <div class="dropdown m-auto mx-3">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>
            </div>

            {% if is_verified %}
            <img src="{{user.profile_url}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
            {% else %}
            <img src="{{user.profile_url}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
            {% endif %}
        </div>
    </div>
</nav>
<div class="h3 text-center m-3">Hello, <span class="fw-bold">{{user.nickname}}</span>!</div>
<div class="h3 text-center m-3">Sorry, <span class="fw-bold">{{user.nickname}}</span>. It seems that
    you are not a verified user. You can't view this page until you are verified.</div>

{% endif %}

</body>
{% endblock content %}

donation/templates/donation_page_user.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Donation</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
<link rel="stylesheet" href="{% static '/donationPageStyle.css' %}" />
<link rel="stylesheet" href="{% static '/invalidButton.css' %}" />
<script src="{% static '/donationPageUserJS.js' %}"></script>
{% endblock meta %}

{% block content %}
<body>
{% if user.is_user %}
    <nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>

        <div class="d-flex flex-row">
            {% if user.is_verified_user %}
            <a class="m-3 btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">Open Donations</a>
            {% endif %}
            <div class="dropdown m-auto mx-3">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>
            </div>
            <!-- Pembeda dari user yang sudah verified dan belum adalah pada border dari profile picture -->
            {% if user.is_verified_user %}
            <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
            {% else %}
            <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
            {% endif %}
        </div>
    </div>
    </nav>
    <div class="h5 text-center m-3">Donations opened by <span class="fw-bold">{{user}}</span></div>

    <!-- Card berisi Donatee -->
    <div class="container my-5">
        <div class="row">
                <div id ="card">

                </div>
        </div>
    </div>

<!-- Modal -->
<div id="modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Open Donations</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="" id="form_modal">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <table>
                        <tr class="fieldWrapper">
                            {{ form.name.errors }}
                            <td class="p m-3">Donatee Name: </td>
                            <td class="m-3">
                                <input type="text" id="{{form.name.id_for_label}}" name="{{form.name.html_name}}"
                                class="form-control{% if form.name.errors %} is-invalid{% endif %}"
                                value="{% if form.name.value %}{{form.name.value}}{% endif %}" placeholder="Name" required>
                            </td>
                        </tr>
                        <tr class="fieldWrapper">
                            {{ form.description.errors }}
                            <td class="p m-3">Description: </td>
                            <td class="m-3">
                                <textarea id="{{form.description.id_for_label}}" name="{{form.description.html_name}}"
                                class="form-control{% if form.description.errors %} is-invalid{% endif %}"
                                value="{% if form.description.value %}{{form.description.value}}{% endif %}" placeholder="Description" required> </textarea>
                            </td>
                        </tr>
                        <tr class="fieldWrapper">
                            {{ form.amountNeeded.errors }}
                            <td class="p m-3">Amount Needed: </td>
                            <td class="p m-3">
                                <input type="number" id="{{form.amountNeeded.id_for_label}}" name="{{form.amountNeeded.html_name}}"
                                       class="form-control{% if form.amountNeeded.errors %} is-invalid{% endif %}"
                                       value="{% if form.amountNeeded.value %}{{form.amountNeeded.value}}{% endif %}" placeholder="Min: 100000" min="100000" required>
                            </td>
                        </tr>
                        <tr>
                            <td class="p m-3"><button id="open" class="btn btn-warning" type="submit" value="Open Donatee" data-bs-dismiss="modal">Open Donatee</button></td>
                        </tr>
                    </table>

                </form>
            </div>
        </div>
    </div>
</div>

    <a class="m-1 btn btn-primary" href="{% url 'donation:show_donation' %}">Back to Donation Page</a>


{% else %}
<nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row">
            <div class="dropdown m-auto mx-3">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>
            </div>

            {% if is_verified %}
            <img src="{{user.profile_url}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
            {% else %}
            <img src="{{user.profile_url}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
            {% endif %}
        </div>
    </div>
</nav>
<div class="h3 text-center m-3">Hello, <span class="fw-bold">{{user.nickname}}</span>!</div>
<div class="h3 text-center m-3">Sorry, <span class="fw-bold">{{user.nickname}}</span>. It seems that
    you are not a verified user. You can't view this page until you are verified.</div>

{% endif %}

</body>
{% endblock content %}