blog/urls.py
from django.urls import path
from blog.views import show_post, post_detail, upload, show_json, addUpvote, addDownvote, show_json_by_tag, show_json_by_id, add_post, show_post_by_tag, show_tag

app_name = 'blog'

urlpatterns = [
    path('', show_post, name='show_post'),
    path('details/', post_detail, name='post_detail'),
    path('add-post/', upload, name='upload'),
    path('add-post-flutter/', add_post, name='add_post'),
    path('show-tag-flutter/<str:tag>', show_post_by_tag, name='show_post_by_tag'),
    path('json/', show_json, name='show_json'),
    path('jsontag/', show_tag, name='show_tag'),
    path('json/<str:tag>', show_json_by_tag, name='show_json_by_tag'),
    path('json/id/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('updateUpvote/<int:id>', addUpvote, name='addUpvote'),
    path('updateDownvote/<int:id>', addDownvote, name='addDownvote'),
]

calorietracker/urls.py
from django.urls import path
from calorietracker.views import show_caloriepage, add_calorie, show_json
from calorietracker.views import reduce_calorie,edit_add,edit_reduce,edit_reduce_save, edit_add_save,delete
from calorietracker.views import calorief, show_jsonf, deletef, edit_reduce_savef, edit_add_savef, deleteAllf
app_name = 'calorietracker'

urlpatterns = [
    path('', show_caloriepage, name='show_caloriepage'),
    path('add_calorie/', add_calorie, name='add_calorie'),
    path('reduce_calorie/', reduce_calorie, name='reduce_calorie'),
    path('json/', show_json, name='show_json'),
    path('edit_add/<int:id>', edit_add, name='edit_add'),
    path('edit_reduce/<int:id>', edit_reduce, name='edit_reduce'),
    path('edit_reduce_save/<int:id>', edit_reduce_save, name='edit_reduce_save'),
    path('edit_add_save/<int:id>', edit_add_save, name='edit_add_save'),
    path('delete/<int:id>', delete, name='delete'),
    path('calorief/', calorief, name='show_jsonf'),
    path('show_jsonf/', show_jsonf, name='show_jsonf'),
    path('deletef/', deletef, name='deletef'),
    path('deleteAllf/', deleteAllf, name='deleteAllf'),
    path('edit_reduce_savef/', edit_reduce_savef, name='edit_reduce_savef'),
    path('edit_add_savef/', edit_add_savef, name='edit_add_savef'),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', show_index, name='show_index'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json-user/', json_user, name='json_user'),
    path('change/<int:id>', change_status_user, name='change_status_user'),
    path('delete/<int:id>', delete_user, name='delete_user'),
    path('profile/', show_profile, name='profile'),
    path('add-message/', add_message, name='add_message'),
    path('json-message/', show_json_message, name='show_json_message'),
    path('delete-msg/<int:id>', delete_message, name='delete_message'),
    path('json-message-name/', show_json_message_with_sender, name='show_json_message_with_sender')
]

nutrious/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('calorietracker/', include('calorietracker.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('foodsharing/', include('foodsharing.urls')),
    path('recipe/', include('recipe.urls')),
    path('auth/', include('authentication.urls'))
]

calorietracker/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from home.models import AppUser



class Calorie(models.Model):
    description = models.TextField()
    category = models.CharField(max_length = 300, default='')
    user = models.ForeignKey(AppUser, on_delete= models.CASCADE)
    calorie= models.IntegerField(default=0,null=True,blank=True)
    date = models.DateTimeField(auto_now_add = True)
    time = models.CharField(max_length = 300, default='')
    is_increasing = models.BooleanField()
    class Meta:
        ordering = ['-date']
    

calorietracker/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from calorietracker.models import Calorie
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
@login_required(login_url='/login/')
def show_caloriepage(request):
	data = Calorie.objects.order_by('-date')
	if request.user.is_authenticated:
		context = {
			'user' : request.user,
			'nickname' : request.user.nickname,
			'user_profile' : request.user.profile_pict_url,
			'data' : data,
	}
	else:
		context = {
			'user' : request.user,
			'data' : data,
		}
	return render(request, 'calorietracker.html',context)

@login_required(login_url='/home/login/')
@csrf_exempt
def add_calorie(request):
	if request.method == "POST":
		calorie = request.POST.get("calorie")
		description = request.POST.get("description")
		category = request.POST.get("category")
		date= request.POST.get('date')
		time= request.POST.get('time')
		Calorie.objects.create(time = time,category = category,is_increasing = True, date =date,calorie= calorie, description = description, user=request.user)
		return HttpResponse()
	else:
		return redirect('calorietracker:show_caloriepage')

@login_required(login_url='/home/login/')
@csrf_exempt
def reduce_calorie(request):
	if request.method == "POST":
		calorie = request.POST.get("calorie")
		description = request.POST.get("description")
		category = request.POST.get("category")
		date= request.POST.get('date')
		time= request.POST.get('time')
		Calorie.objects.create(time = time,category = category,is_increasing = False, date =date,calorie= calorie, description = description, user=request.user)

		return HttpResponse()
	else:
		return redirect('calorietracker:show_caloriepage')

def show_json(request):
    data =Calorie.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")   

def edit_add(request, id):
    edit = Calorie.objects.get(pk = id)
    context = {
        'edit' : edit,
		'user_profile' : request.user.profile_pict_url,
    }
    return render(request, "edit.html", context)
def edit_reduce(request, id):
    edit = Calorie.objects.get(pk = id)
    context = {
        'edit' : edit,
		'user_profile' : request.user.profile_pict_url,
    }
    return render(request, "edit_reduce.html", context)
def edit_reduce_save(request, id):
	if request.method == "POST":
		x = Calorie.objects.get(pk = id)
		x.calorie = request.POST['calorie']
		x.description = request.POST['description']
		
		x.save()
		
		return redirect('calorietracker:show_caloriepage')
def edit_add_save(request, id):
	if request.method == "POST":
		x = Calorie.objects.get(pk = id)
		x.calorie = request.POST['calorie']
		x.description = request.POST['description']
		x.category = request.POST['category']
		x.save()
		
		return redirect('calorietracker:show_caloriepage')
def delete(request, id):
	edit = Calorie.objects.get(pk = id)
	edit.delete()
	return redirect('calorietracker:show_caloriepage')


@csrf_exempt
def calorief(request):
	if (request.method == 'POST'):
		calorie =int(request.POST.get("calorie")) 
		description = request.POST.get("description")
		category = request.POST.get("category")
		is_increasing_ = request.POST.get("is_increasing")
		date = request.POST.get("date")
		time =  request.POST.get("time")
		if(is_increasing_ =="false"):
			is_increasing = False
		else:
			is_increasing = True
		user = request.user
		obj_baru = Calorie(user = user, calorie=calorie, description = description, category = category,is_increasing = is_increasing, time=time, date=date)
		obj_baru.save()
		return JsonResponse({'status': 'berhasil dibuka'}, status=200)

@login_required(login_url='/login/')
def show_jsonf(request):
	list_of_calorie = []
	calories= Calorie.objects.filter(user=request.user)
	for calorie in calories:
		calorie_instance = {}
		calorie_instance["pk"] = calorie.id
		calorie_instance["calorie"] = calorie.calorie
		calorie_instance["description"] = calorie.description
		calorie_instance["category"] = calorie.category
		calorie_instance["is_increasing"] = calorie.is_increasing
		calorie_instance["date"] = calorie.date
		calorie_instance["time"] = calorie.time 
		list_of_calorie.append(calorie_instance)
	return JsonResponse({"data": list_of_calorie})

@csrf_exempt
def deletef(request):
    if (request.method == 'POST'):
        id = request.POST.get('id')
        Calorie.objects.get(pk=int(id)).delete()
        return JsonResponse({'status': 'berhasil ditutup'}, status=200)
@csrf_exempt
def deleteAllf(request):
	Calorie.objects.filter(user=request.user).delete()
	
	return JsonResponse({'status': 'berhasil ditutup'}, status=200)

@csrf_exempt
def edit_reduce_savef(request):
	if (request.method == 'POST'):
		id = request.POST.get('id')
		x = Calorie.objects.get(pk=int(id))
		x.calorie = int(request.POST.get("calorie")) 
		x.description = request.POST.get("description")
		x.save()
		return JsonResponse({"data": "success"})

@csrf_exempt
def edit_add_savef(request):
	if (request.method == 'POST'):
		id = request.POST.get('id')
		x = Calorie.objects.get(pk=int(id))
		x.calorie = int(request.POST.get("calorie")) 
		x.description = request.POST.get("description")
		x.category = request.POST.get("category")
		x.save()
		return JsonResponse({"data": "success"})

calorietracker/templates/calorietracker.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
<script src="{% static '/caloriePageJS.js' %}"></script>
<link rel="stylesheet" href="{% static '/caloriePageStyle.css' %}" />
<title>Calorie Tracker</title>
{% endblock meta %}
{% block content %}
    <body>
        <nav class="navbar shadow navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home:show_index' %}">
                    <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
                </a>
                <div class="d-flex flex-row">
                    
                        <button type="button"  class="btn button p-2 m-1" data-bs-toggle="modal" data-bs-target="#Modal" id="Test">
                            Add Calorie
                        </button>
                        <button type="button"  class="btn button p-2 m-1"data-bs-toggle="modal" data-bs-target="#Modal1" id="Test1">
                            Reduce Calorie
                        </button>
                    <div class="dropdown m-auto mx-3">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Profile
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                        </ul>
                    </div>
                     <!-- Pembeda dari user yang sudah verified dan belum adalah pada border dari profile picture -->
                    {% if user.is_verified_user %}
                    <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
                    {% else %}
                    <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
                    {% endif %}
                </div>
            </div>
        </nav>
        <div>
            <form method="POST">
                {% csrf_token %}
                <br>
                <br> 
                <div class="text-center">
                    <h1 class="fw-bold">Welcome to Calorie Tracker, {{nickname}} !</h1>
                    <br>
                    <p>This is your calorie tracker for today</p>
                    <p>Refresh page to delete your yesterday calorie tracker</p>
                    <p id="date-info"></p>
                    <br>
                </div>
                <div class="row align-items-center justify-content-center text-center">
                    <div  style="width: 18rem;">
                      <div class="card mb-3 card-calorie">
                        <div class="card-body">
                          <h5 class="card-title">Calories you have consumed</h5>
                          <div class="card-text" id="counter_add"></div>
                        </div>
                      </div>
                    </div>
                    <div  style="width: 18rem;">
                        <div class="card mb-3 card-calorie">
                          <div class="card-body">
                            <h5 class="card-title">Calories you have burned</h5>
                            <div class="card-text" id="counter_decrease"></div>
                          </div>
                        </div>
                    </div>
                    <div  style="width: 18rem;">
                        <div class="card mb-3 card-calorie">
                          <div class="card-body">
                            <h5 class="card-title">Your total accumulated calories</h5>
                            <div class="card-text" id="total"></div>
                          </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="modal" tabindex="-1" id="Modal" >
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h3 class="modal-title w-100 text-center fw-bold pl-100">Add calorie</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button>
                        </div>
                        <div class="modal-body">
                            <td>Calorie</td>
                            <td><input type="number" name="calorie" min="0" placeholder="Calorie" class="form-control" id="input_calorie"  oninput="validity.valid||(value='');"/></td>
                            <br>
                            <td>Deskripsi </td>
                            <textarea name="deskripsi" placeholder="Deskripsi" style="min-height: 100px" class="form-control" id="input_deskripsi"></textarea>
                            <br>
                            <label for="category">Choose a category:</label>
                            <select name="category" id="category">
                                <option value="Breakfast">Breakfast</option>
                                <option value="Lunch">Lunch</option>
                                <option value="Dinner">Dinner</option>
                                <option value="Snack">Snack</option>
                            </select>
                        </div>
                        <div class="modal-footer">
                            <button id="add" class="btn button"  data-dismiss="modal">Add Calorie</button>
                            <button type="button" class="btn btn-secondary"  data-bs-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                </div>

                <div class="modal" tabindex="-1" id="Modal1">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                            <h3 class="modal-title w-100 text-center fw-bold pl-100">Reduce calorie</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button>
                        </div>
                        <div class="modal-body">
                            <td>Calorie</td>
                            <td><input type="number" name="calorie"  min="0" placeholder="Calorie" class="form-control" id="input_calorie1" oninput="validity.valid||(value='');"/></td>
                            <br>
                            <td>Deskripsi </td>
                            <textarea name="deskripsi" placeholder="Deskripsi" style="min-height: 100px" class="form-control" id="input_deskripsi1" ></textarea>
                        </div>
                        <div class="modal-footer">
                            <button id="decrease" class="btn button"  data-dismiss="modal">Reduce Calorie</button>
                            <button type="button" class="btn btn-secondary"  data-bs-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                </div>


                <div class="container">
                    <div class="row no-gutters">
                            <div id ="card"></div>
                    </div>
                </div>
                
            </form>
        </div>

    </body>
{% endblock content %}

calorietracker/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="{% static '/editPageStyle.css' %}" />
<title>Calorie Tracker</title>
<script>
$(document).ready(function(data){
    var data = ("{{edit.category}}");
     $("#category").val(data);
});
</script>
{% endblock meta %}
{% block content %}
<nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:show_index' %}">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row">
            <div class="dropdown m-auto mx-3">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>
            </div>
             <!-- Pembeda dari user yang sudah verified dan belum adalah pada border dari profile picture -->
             {% if user.is_verified_user %}
             <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
             {% else %}
             <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
             {% endif %}
        </div>
    </div>
</nav>
<body>
    <div class="container p-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-5">
                <div class="card bg-white text-dark shadow-lg border-0" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class = "login">
                            <h1 class="title fw-bold">Edit data</h1>
                                <form method="POST" action="{% url 'calorietracker:edit_add_save' edit.id %}">
                                    {% csrf_token %}
                                     
                                    <td>Calorie</td>
                                    <td><input type="number" name="calorie" min="0" value="{{edit.calorie}}" class="form-control" id="input_calorie"  oninput="validity.valid||(value='');"/></td>

                                    <td>Deskripsi </td>
                                    <input type="text" name="description" value="{{edit.description}}" s style="min-height: 100px" class="form-control" id="input_deskripsi"></input>
                                    
                                   
                                    <br>
                                    <label for="category">Choose a category:</label>
                                    <select name="category" id="category">
                                        <option value="Breakfast">Breakfast</option>
                                        <option value="Lunch">Lunch</option>
                                        <option value="Dinner">Dinner</option>
                                        <option value="Snack">Snack</option>
                                    </select>
                                    <div><br><button class="btn login_btn btn-primary mx-auto m-1" type="submit" value="Edit">Edit</button></div>
                            </form> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

calorietracker/templates/edit_reduce.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="{% static '/editPageStyle.css' %}" />
<title>Calorie Tracker</title>
{% endblock meta %}
{% block content %}
<nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:show_index' %}">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row">
            <div class="dropdown m-auto mx-3">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>
            </div>
             <!-- Pembeda dari user yang sudah verified dan belum adalah pada border dari profile picture -->
             {% if user.is_verified_user %}
             <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
             {% else %}
             <img src="{{user_profile}}" class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
             {% endif %}
        </div>
    </div>
</nav>
<body>
    <div class="container p-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-5">
                <div class="card bg-white text-dark shadow-lg border-0" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class = "login">
                            <h1 class="title fw-bold">Edit data</h1>
                                <form method="POST" action="{% url 'calorietracker:edit_reduce_save' edit.id %}">
                                    {% csrf_token %}
                                    
                          
                         
                           
                                    <td>Calorie</td>
                                    <td><input type="number" name="calorie" min="0" value="{{edit.calorie}}" class="form-control" id="input_calorie"  oninput="validity.valid||(value='');"/></td>

                                    
                                    <td>Deskripsi </td>
                                    <input type="text" name="description" value="{{edit.description}}" s style="min-height: 100px" class="form-control" id="input_deskripsi"></input>
                                    
                                   
                                    <div><br><button class="btn login_btn btn-primary mx-auto m-1" type="submit" value="Edit">Edit</button></div>
                                 
                                </form> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}