blog/urls.py
from django.urls import path
from blog.views import show_post, post_detail, upload, show_json, addUpvote, addDownvote, show_json_by_tag, show_json_by_id, add_post, show_post_by_tag, show_tag

app_name = 'blog'

urlpatterns = [
    path('', show_post, name='show_post'),
    path('details/', post_detail, name='post_detail'),
    path('add-post/', upload, name='upload'),
    path('add-post-flutter/', add_post, name='add_post'),
    path('show-tag-flutter/<str:tag>', show_post_by_tag, name='show_post_by_tag'),
    path('json/', show_json, name='show_json'),
    path('jsontag/', show_tag, name='show_tag'),
    path('json/<str:tag>', show_json_by_tag, name='show_json_by_tag'),
    path('json/id/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('updateUpvote/<int:id>', addUpvote, name='addUpvote'),
    path('updateDownvote/<int:id>', addDownvote, name='addDownvote'),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', show_index, name='show_index'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json-user/', json_user, name='json_user'),
    path('change/<int:id>', change_status_user, name='change_status_user'),
    path('delete/<int:id>', delete_user, name='delete_user'),
    path('profile/', show_profile, name='profile'),
    path('add-message/', add_message, name='add_message'),
    path('json-message/', show_json_message, name='show_json_message'),
    path('delete-msg/<int:id>', delete_message, name='delete_message'),
    path('json-message-name/', show_json_message_with_sender, name='show_json_message_with_sender')
]

nutrious/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('calorietracker/', include('calorietracker.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('foodsharing/', include('foodsharing.urls')),
    path('recipe/', include('recipe.urls')),
    path('auth/', include('authentication.urls'))
]

recipe/urls.py
from django.urls import path
from recipe.views import show_recipe, add_recipe, show_json, delete, add_recipe_flutter

app_name = 'recipe'

urlpatterns = [
    path('', show_recipe, name='show_recipe'),
    path('add/', add_recipe, name='add_recipe'),
    path('add-flutter/', add_recipe_flutter, name='add_recipe_flutter'),
    path('delete/<int:id>', delete, name='delete'),
    path('json/', show_json, name='show_json'),
]

recipe/models.py
from django.db import models

from home.models import AppUser

class FoodRecipe(models.Model):
    food_name= models.CharField(max_length=100)
    author = models.ForeignKey(AppUser, on_delete= models.CASCADE)
    author_name =models.CharField(max_length=100)
    ingredients = models.TextField()
    method = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    formatted_date = models.CharField(max_length=20)

    class Meta:
        ordering = ['-created_on']

recipe/forms.py
from recipe.models import FoodRecipe
from django.forms import ModelForm

class CreateRecipe(ModelForm):
    class Meta:
        model = FoodRecipe
        fields = ('food_name', 'author', 'ingredients', 'method', 'created_on')
        exclude = ['author', 'created_on']

recipe/views.py
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from recipe.models import FoodRecipe


@csrf_exempt
def show_recipe(request):
    data_recipe = FoodRecipe.objects.order_by('-created_on')
    context = {
        'recipe_list' : data_recipe
    }
    return render(request, "recipes.html", context)


def show_json(request):
    data = FoodRecipe.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def add_recipe(request):
    if request.method == 'POST':
        food_name = request.POST.get('food_name')
        ingredients = request.POST.get('ingredients').strip().replace("\n", "</li> <li>" )
        method = request.POST.get('method').strip().replace("\n", "</li> <li>" )
        date = datetime.datetime.now()
        formatted_date = formatted_date = date.strftime("%d") + " " + date.strftime("%B") + " " + date.strftime("%Y")

        new_recipe = FoodRecipe(food_name=food_name, ingredients=ingredients, method=method, author=request.user, author_name=request.user.username, created_on=date, formatted_date=formatted_date)
        new_recipe.save()

        return HttpResponse(b"CREATED", status=201)


@csrf_exempt
def delete(request, id):
    food = FoodRecipe.objects.get(pk=id)
    if(request.user == food.author):
        food.delete()
    return redirect('recipe:show_recipe')

@csrf_exempt
def add_recipe_flutter(request):
    if request.method == 'POST':
        food_name = request.POST.get('food_name')
        ingredients = request.POST.get('ingredients').strip().replace("\n", "</li> <li>" )
        method = request.POST.get('method').strip().replace("\n", "</li> <li>" )
        date = datetime.datetime.now()
        formatted_date = date.strftime("%d") + " " + date.strftime("%B") + " " + date.strftime("%Y")

        new_recipe = FoodRecipe(food_name=food_name, ingredients=ingredients, method=method, author=request.user, author_name=request.user.username, created_on=date, formatted_date=formatted_date)
        new_recipe.save()

        data = {"succesed"}

        return JsonResponse(json.loads(data), safe=False)

recipe/templates/recipes.html
{% extends 'base.html' %}

{% load static %}


{% block meta %}
<title>Food Recipes</title>

<!-- Preload for faster image load -->
<link rel="preload" as="image" href="{% static 'recipe-header.png' %}">

<!-- Styling -->
<!-- <link rel="stylesheet" href="{% static '/recipe.css' %}"> -->
<style>
  .avatar {
    width: 50px;
    height: 50px;
    object-fit: cover;
}

.header-content {
    /* background-image: url("{% static 'recipe-header.png' %}"); */
    background-image: url("../static/recipe-header.png");
    
    transition: transform .2s;
    background-size: cover;
    background-repeat: no-repeat;
}

.card:hover {
    transform: scale(1.02);
    box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
    opacity: 1.0;
}

.row {
    margin-left: 75px;
    margin-right: 75px;
}

@media screen and (max-width: 900px) {
    #column {
        width: 100%;
        display: flex;
        justify-content: space-between;
        flex-direction: column;
        margin-bottom: 20px;
    }
}
</style>
    
{% endblock meta %}


{% block content %}

<!-- Navbar -->
{% if user.is_authenticated %}
<nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:show_index' %}">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row">
            <div class="dropdown m-auto mx-3">
                <button type="button" class="btn btn-success" data-bs-toggle="modal"
                    data-bs-target=".bd-example-modal-lg" data-bs-whatever="@getbootstrap">Add recipe</button>
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'home:profile' %}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'home:logout' %}">Log Out</a></li>
                </ul>

                <!-- Pembeda dari user yang sudah verified dan belum adalah pada border dari profile picture -->
                {% if user.is_verified_user %}
                <img src="{{user.profile_pict_url}}"
                    class="rounded-circle shadow avatar m-auto mx-3 border border-success border-3">
                {% else %}
                <img src="{{user.profile_pict_url}}"
                    class="rounded-circle shadow avatar m-auto mx-3 border border-danger border-3">
                {% endif %}

            </div>
        </div>
    </div>
</nav>
{% else %}
<nav class="navbar shadow navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:show_index' %}">
            <img src="{% static 'NUTRIOUS.png' %}" alt="Logo" height="70" class="d-inline-block align-text-top">
        </a>
        <div class="d-flex flex-row-reverse ">
            <a class="btn btn-outline-primary p-2 m-3" role="button" href="{% url 'home:register' %}">Sign Up</a>
            <a class="btn btn-outline-success p-2 m-3" role="button" href="{% url 'home:login' %}">Log In</a>
            <a class="btn btn-success p-2 m-3" role="button" href="{% url 'home:login' %}">Add Recipe</a>
        </div>
    </div>
</nav>
{% endif %}

<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" aria-labelledby="myLargeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-white text-black">

            <div class="modal-header">

                <h3 class="modal-title w-100 text-center fw-bold pl-100">Create Recipe</h3>

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form style="text-align:center" id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="col mx-3">

                        <div class="form-group row my-2">
                            <label for="formInput">Menu name</label>
                            <input type="text" class="form-control" id="formInput" name="food_name" required>
                        </div>

                        <div class="form-group row my-2">
                            <label for="formInput2">Ingredients</label>
                            <textarea rows="7" type="text" class="form-control" id="formInput2" name="ingredients"
                                required></textarea>
                        </div>

                        <div class="form-group row my-2">
                            <label for="formInput2">How to make it?</label>
                            <textarea rows="7" type="text" class="form-control" id="formInput3" name="method"
                                required></textarea>
                        </div>

                        <button class="btn btn-success btn-lg px-py-5 row my-2" id="addButton" type="submit"
                            value="Submit">Add Recipe</button></td>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>


<!-- Header -->
<div class="card m-3 p-5 header-content text-light">
    <div class="text-center fw-bold h1 m-2">Food Recipes</div>
    <div class="text-center m-2">Find your food inspirations and make your own food here. You can also help others by
        posting your own recipes ;)</div>
</div>


<!-- Row -->
<div class="row" id="card-row">
</div>


<!-- Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    async function getRecipe() {
        return fetch("{% url 'recipe:show_json' %}").then((res) => res.json())
    }

    async function refreshRecipe() {
        document.getElementById("card-row").innerHTML = ""
        const recipes = await getRecipe()
        let htmlString = ``
        recipes.forEach((item) => {
            htmlString += `\n<div id="column" class="col-4">
        <div class="card border-success text-dark bg-white mb-3" style="max-width: 28rem;" id="card-task">
            <div class="card-header">
                <h3><b>${item.fields.food_name}</b></h3>
                <h6 class="card-subtitle mb-2">— by ${item.fields.author_name}, ${item.fields.formatted_date}</h6>
            </div>

            <div class="card-body">
                <p class="card-text"><u>Ingredients: </u></p>
                <ul class="card-text"><li>${item.fields.ingredients}</li></ul>
                <p class="card-text"><u>Step by step:</u></p>
                <ol class="card-text"><li>${item.fields.method}</li></ol>
            </div>
        </div>
        </div>`
        })

        document.getElementById("card-row").innerHTML = htmlString
    }

    async function addRecipe() {
        var txt = document.getElementById("formInput").value;
        var txt2 = document.getElementById("formInput2").value;
        var txt3 = document.getElementById("formInput3").value;
        console.log(txt);
        console.log(txt2);
        console.log(txt3);
        if (txt != "" && txt2 != "" && txt3 != "") {
            fetch("{% url 'recipe:add_recipe' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshRecipe);
            $('#modal').modal('hide');
            document.getElementById("form").reset();
        }

        return false
    }

    document.getElementById("addButton").onclick = addRecipe
    refreshRecipe()

</script>


{% endblock content %}